jobs:
  build:
    name: Java ${{ matrix.java }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3.5.3
    - continue-on-error: true
      name: Set up Java
      uses: actions/setup-java@v3.12.0
      with:
        distribution: zulu
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      name: Build with Maven
      run: mvn -B package --file pom.xml -Prelease,headless
    strategy:
      matrix:
        java:
        - 11
name: Java CI with Maven
on:
  repository_dispatch:
    types: trigger-ga___maven.yml
